#!/bin/sh

case "$1" in
    start)
        echo "Starting ldd modules"
        
        # Navigate to the folder where Buildroot installed the .ko files
        cd /lib/modules/$(uname -r)/extra
        
        /usr/bin/scull_load
        /usr/bin/module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Stopping ldd modules"
        /usr/bin/scull_unload
        /usr/bin/module_unload faulty
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
