name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
  full-test:
    container: cuaesd/aesd-autotest:24-assignment5-buildroot
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Patch QEMU mkvenv script in Buildroot
        run: |
          python3 -c '
          with open("buildroot/package/qemu/qemu.mk", "a") as f:
              f.write("\ndefine HOST_QEMU_PATCH_MKVENV\n\tsed -i \"s/maker = distlib.scripts.ScriptMaker(None, bin_path)/return/g\" $(@D)/python/scripts/mkvenv.py\nendef\nHOST_QEMU_POST_EXTRACT_HOOKS += HOST_QEMU_PATCH_MKVENV\n")
          '
      - name: Run full test
        env:
            GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: ./full-test.sh
      - name: Cleanup
        if: always()
        run: |
          ssh-add -D
